<?php
/**
 * Language labels for database tables/fields belonging to extension "sr_feuser_register"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'tt_content.list_type' => 'Front End User Registration',
		'tt_content.pi1_flexform.display_mode' => 'Display mode',
		'tt_content.pi1_flexform.display_mode.1' => 'Not set',
		'tt_content.pi1_flexform.display_mode.3' => 'Create',
		'tt_content.pi1_flexform.display_mode.5' => 'Invite',
		'tt_content.pi1_flexform.display_mode.7' => 'Edit',
		'fe_users.static_info_country' => 'Country:',
		'fe_users.zone' => 'State/province:',
		'fe_users.language' => 'Language:',
		'fe_users.first_name' => 'First Name:',
		'fe_users.last_name' => 'Last Name:',
		'fe_users.date_of_birth' => 'Date of birth:',
		'fe_users.gender' => 'Mr/Ms:',
		'fe_users.gender.I.0' => 'Mr',
		'fe_users.gender.I.1' => 'Ms',
		'fe_users.status' => 'Status:',
		'fe_users.status.I.1' => 'Student',
		'fe_users.status.I.2' => 'Job seeking',
		'fe_users.status.I.3' => 'Working',
		'fe_users.status.I.4' => 'Retired',
		'fe_users.comments' => 'Comments:',
		'fe_users.by_invitation' => 'Was invited:',
		'fe_groups_language_overlay' => 'User Group Alternative Language',
		'fe_groups_language_overlay.title' => 'Translated user group name',
	),
	'dk' => Array (
		'tt_content.list_type' => 'Front End Bruger Registrering',
		'fe_users.static_info_country' => 'Land:',
		'fe_users.zone' => 'Stat/Provins/Amt:',
		'fe_users.language' => 'Sprog:',
		'fe_users.first_name' => 'Fornavn(e):',
		'fe_users.last_name' => 'Efternavn:',
		'fe_users.date_of_birth' => 'Fшdselsdato',
		'fe_users.gender' => 'Hr./Fru:',
		'fe_users.gender.I.0' => 'Hr.',
		'fe_users.gender.I.1' => 'Fru',
		'fe_users.status' => 'Status:',
		'fe_users.status.I.1' => 'Studerende',
		'fe_users.status.I.2' => 'Jobsшgende',
		'fe_users.status.I.3' => 'Arbejdende',
		'fe_users.status.I.4' => 'Pensioneret',
		'fe_users.comments' => 'Kommentarer:',
		'tt_content.pi1_flexform.display_mode' => 'Visningsmetode',
		'tt_content.pi1_flexform.display_mode.1' => 'Ikke defineret',
		'tt_content.pi1_flexform.display_mode.3' => 'Opret',
		'tt_content.pi1_flexform.display_mode.5' => 'Inviter',
		'tt_content.pi1_flexform.display_mode.7' => 'Rediger',
		'fe_users.by_invitation' => 'Var inviteret:',
		'fe_groups_language_overlay' => 'Alternativt sprog for brugergruppe',
		'fe_groups_language_overlay.title' => 'Oversat brugergruppe navn',
	),
	'de' => Array (
		'tt_content.list_type' => 'Front End Benutzer Registrierung',
		'fe_users.static_info_country' => 'Land:',
		'fe_users.zone' => 'Bundesland / Staat / Provinz:',
		'fe_users.language' => 'Sprache:',
		'fe_users.first_name' => 'Vorname:',
		'fe_users.last_name' => 'Nachname:',
		'fe_users.date_of_birth' => 'Geburtsdatum:',
		'fe_users.gender' => 'Hr./Fr.:',
		'fe_users.gender.I.0' => 'Hr.',
		'fe_users.gender.I.1' => 'Fr.',
		'fe_users.status' => 'Status:',
		'fe_users.status.I.1' => 'Student',
		'fe_users.status.I.2' => 'Schьler',
		'fe_users.status.I.3' => 'Angestellt',
		'fe_users.status.I.4' => 'Selbststдndig',
		'fe_users.comments' => 'Kommentare:',
	),
	'no' => Array (
		'tt_content.list_type' => 'Registering av Front End brukere',
		'tt_content.pi1_flexform.display_mode' => 'Visningsmеte',
		'tt_content.pi1_flexform.display_mode.1' => 'Lag',
		'tt_content.pi1_flexform.display_mode.3' => 'Inviter',
		'tt_content.pi1_flexform.display_mode.5' => 'Bekreft',
		'tt_content.pi1_flexform.display_mode.7' => 'Endre',
		'fe_users.static_info_country' => 'Land:',
		'fe_users.zone' => 'Fylke:',
		'fe_users.language' => 'Sprеk:',
		'fe_users.first_name' => 'Fornavn:',
		'fe_users.last_name' => 'Etternavn:',
		'fe_users.date_of_birth' => 'Fшdt dato:',
		'fe_users.gender' => 'Herr/Fru:',
		'fe_users.gender.I.0' => 'Herr',
		'fe_users.gender.I.1' => 'Fru',
		'fe_users.status' => 'Status',
		'fe_users.status.I.1' => 'Student',
		'fe_users.status.I.2' => 'Arbeidssшker',
		'fe_users.status.I.3' => 'Yrkesaktiv',
		'fe_users.status.I.4' => 'Pensjonert',
		'fe_users.comments' => 'Kommentarer:',
		'fe_users.by_invitation' => 'Ble invitert:',
		'fe_groups_language_overlay' => 'Alternativt sprеk for brukergruppe',
		'fe_groups_language_overlay.title' => 'Oversatt brukergruppe navn',
	),
	'it' => Array (
		'tt_content.list_type' => 'Registrazione Utenti Frontend',
		'fe_users.static_info_country' => 'Stato:',
		'fe_users.zone' => 'Provincia:',
		'fe_users.language' => 'Lingua:',
		'fe_users.first_name' => 'Nome:',
		'fe_users.last_name' => 'Cognome:',
		'fe_users.date_of_birth' => 'Data di nascita:',
		'fe_users.gender' => 'Signor/Signora:',
		'fe_users.gender.I.0' => 'Signor',
		'fe_users.gender.I.1' => 'Signora',
		'fe_users.status' => 'Situazione lavorativa:',
		'fe_users.status.I.1' => 'Studente',
		'fe_users.status.I.2' => 'In cerca di lavoro',
		'fe_users.status.I.3' => 'Occupato',
		'fe_users.status.I.4' => 'Pensionato',
		'fe_users.comments' => 'Commenti',
		'fe_groups_language_overlay' => 'Gruppo Utenti: lingua alternativa',
		'fe_groups_language_overlay.title' => 'Gruppo Utenti (tradotto):',
	),
	'fr' => Array (
		'tt_content.list_type' => 'Enregistrement des utilisateurs de l\'avant-plan',
		'tt_content.pi1_flexform.display_mode' => 'Mode d\'affichage',
		'tt_content.pi1_flexform.display_mode.1' => 'Non spйcifiй',
		'tt_content.pi1_flexform.display_mode.3' => 'Crйation',
		'tt_content.pi1_flexform.display_mode.5' => 'Invitation',
		'tt_content.pi1_flexform.display_mode.7' => 'Mise а jour',
		'fe_users.static_info_country' => 'Pays:',
		'fe_users.zone' => 'Йtat/province:',
		'fe_users.language' => 'Langue:',
		'fe_users.first_name' => 'Prйnom:',
		'fe_users.last_name' => 'Nom:',
		'fe_users.date_of_birth' => 'Date de naissance:',
		'fe_users.gender' => 'M./Mme:',
		'fe_users.gender.I.0' => 'M.',
		'fe_users.gender.I.1' => 'Mme',
		'fe_users.status' => 'Statut:',
		'fe_users.status.I.1' => 'Aux йtudes',
		'fe_users.status.I.2' => 'En recherche d\'emploi',
		'fe_users.status.I.3' => 'Au travail',
		'fe_users.status.I.4' => 'А la retraite',
		'fe_users.comments' => 'Commentaires:',
		'fe_users.by_invitation' => 'Invitй(e):',
		'fe_groups_language_overlay' => 'Langue alternative de groupe d\'utilisateurs',
		'fe_groups_language_overlay.title' => 'Traduction du nom de groupe',
	),
	'es' => Array (
		'tt_content.list_type' => 'Registro de los usuarios del frontend',
		'fe_users.static_info_country' => 'Paнs:',
		'fe_users.zone' => 'Estado/provincia:',
		'fe_users.language' => 'Idioma:',
		'fe_users.first_name' => 'Nombre:',
		'fe_users.last_name' => 'Apellido:',
		'fe_users.date_of_birth' => 'Fecha de nacimiento:',
		'fe_users.gender' => 'Sr./Sra.:',
		'fe_users.gender.I.0' => 'Sr.',
		'fe_users.gender.I.1' => 'Sra.',
		'fe_users.status' => 'Estado:',
		'fe_users.status.I.1' => 'Estudiantes',
		'fe_users.status.I.2' => 'Buscando trabajo',
		'fe_users.status.I.3' => 'Trabajando',
		'fe_users.status.I.4' => 'Jubilado',
		'fe_users.comments' => 'Comentarios:',
	),
	'nl' => Array (
		'tt_content.list_type' => 'Frontend Gebruikersregistratie',
		'fe_users.static_info_country' => 'Land:',
		'fe_users.zone' => 'Provincie:',
		'fe_users.language' => 'Taal:',
		'fe_users.first_name' => 'Voornaam:',
		'fe_users.last_name' => 'Achternaam:',
		'fe_users.date_of_birth' => 'Geboortedatum:',
		'fe_users.gender' => 'Dhr/Mevr:',
		'fe_users.gender.I.0' => 'Dhr',
		'fe_users.gender.I.1' => 'Mevr',
		'fe_users.status' => 'Status:',
		'fe_users.status.I.1' => 'Student',
		'fe_users.status.I.2' => 'Op zoek naar een baan',
		'fe_users.status.I.3' => 'Werkend',
		'fe_users.status.I.4' => 'Met pensioen',
		'fe_users.comments' => 'Commentaar:',
	),
	'cz' => Array (
		'tt_content.list_type' => 'Registrace uћivatelщ frontendu',
		'fe_users.static_info_country' => 'Zemм:',
		'fe_users.zone' => 'Stбt/kraj:',
		'fe_users.language' => 'Jazyk:',
		'fe_users.first_name' => 'Jmйno:',
		'fe_users.last_name' => 'Pшнjmenн:',
		'fe_users.date_of_birth' => 'Datum narozenн',
		'fe_users.gender' => 'Muћ/Ћena:',
		'fe_users.gender.I.0' => 'muћ',
		'fe_users.gender.I.1' => 'ћena',
		'fe_users.status' => 'Stav:',
		'fe_users.status.I.1' => 'Student',
		'fe_users.status.I.2' => 'Nezamмstnanэ',
		'fe_users.status.I.3' => 'Zamмstnanэ',
		'fe_users.status.I.4' => 'V dщchodu',
		'fe_users.comments' => 'Poznбmky',
	),
	'pl' => Array (
		'tt_content.list_type' => 'Rejesteracja uїytkownikуw zewnкtrznych',
		'fe_users.static_info_country' => 'Kraj:',
		'fe_users.zone' => 'Wojewуdztwo:',
		'fe_users.language' => 'Jкzyk:',
		'fe_users.first_name' => 'Imiк:',
		'fe_users.last_name' => 'Nazwisko:',
		'fe_users.module_sys_dmail_html' => 'Otrzymuje emaile w HTML?',
		'fe_users.date_of_birth' => 'Data urodzenia',
	),
	'si' => Array (
	),
	'fi' => Array (
		'tt_content.list_type' => 'FE kдyttдjдn rekisterцinti',
		'fe_users.static_info_country' => 'Maa:',
		'fe_users.zone' => 'Osavaltio/provinssi:',
		'fe_users.language' => 'Kieli:',
		'fe_users.first_name' => 'Etunimi:',
		'fe_users.last_name' => 'Sukunimi:',
		'fe_users.date_of_birth' => 'Syntymдaika:',
		'fe_users.gender' => 'Mr/Ms:',
		'fe_users.gender.I.0' => 'Mr',
		'fe_users.gender.I.1' => 'Ms',
		'fe_users.status' => 'Tila:',
		'fe_users.status.I.1' => 'Opiskelija',
		'fe_users.status.I.2' => 'Tyцtцn',
		'fe_users.status.I.3' => 'Tyцtekijд',
		'fe_users.status.I.4' => 'Elдkelдinen',
		'fe_users.comments' => 'Kommentit:',
	),
	'tr' => Array (
		'tt_content.list_type' => 'Websitesi Kullanэcэ Kayэt Эюlemi',
		'fe_users.static_info_country' => 'Ьlke:',
		'fe_users.zone' => 'Eyalet/Эl:',
		'fe_users.language' => 'Dil:',
		'fe_users.first_name' => 'Ad:',
		'fe_users.last_name' => 'Soyad:',
		'fe_users.date_of_birth' => 'Doрum tarihi:',
		'fe_users.gender' => 'Bay/Bayan',
		'fe_users.gender.I.0' => 'Bay',
		'fe_users.gender.I.1' => 'Bayan',
		'fe_users.status' => 'Mesleрi:',
		'fe_users.status.I.1' => 'Црrenci',
		'fe_users.status.I.2' => 'Эю arayan',
		'fe_users.status.I.3' => 'Зalэюan',
		'fe_users.status.I.4' => 'Emekli',
		'fe_users.comments' => 'Yorumlar:',
		'fe_groups_language_overlay' => 'Kullanэcэ Grubu Alternatif Dili',
		'fe_groups_language_overlay.title' => 'Зevrilen kullanэcэ grubu adэ',
	),
	'se' => Array (
		'tt_content.list_type' => 'Registrering av Front End-anvдndare',
		'fe_users.static_info_country' => 'Land:',
		'fe_users.zone' => 'Stat/provins:',
		'fe_users.language' => 'Sprеk:',
		'fe_users.first_name' => 'Fцrnamn:',
		'fe_users.last_name' => 'Efternamn:',
		'fe_users.module_sys_dmail_html' => 'Ta emot epost i HTML-format?',
		'fe_users.date_of_birth' => 'Fцdelsetid:',
	),
	'pt' => Array (
	),
	'ru' => Array (
		'tt_content.list_type' => 'Регистрация пользователей на веб-сайте',
		'fe_users.static_info_country' => 'Страна:',
		'fe_users.zone' => 'Район/область:',
		'fe_users.language' => 'Язык:',
		'fe_users.first_name' => 'Имя:',
		'fe_users.last_name' => 'Фамилия:',
		'fe_users.date_of_birth' => 'Дата рождения:',
		'fe_users.gender' => 'Господин / Госпожа:',
		'fe_users.gender.I.0' => 'Господин',
		'fe_users.gender.I.1' => 'Госпожа',
		'fe_users.status' => 'Статус',
		'fe_users.status.I.1' => 'Студент',
		'fe_users.status.I.2' => 'Ищущий работу',
		'fe_users.status.I.3' => 'Работающий',
		'fe_users.status.I.4' => 'Пенсионер',
		'fe_users.comments' => 'Комментарии:',
		'fe_groups_language_overlay' => 'Альтернативный язык группы пользователей',
		'fe_groups_language_overlay.title' => 'Переведённое название группы',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
		'tt_content.list_type' => 'Registracija frontend korisnika:',
		'fe_users.static_info_country' => 'Drћava:',
		'fe_users.zone' => 'Regija/ћupanija:',
		'fe_users.language' => 'Jezik:',
		'fe_users.first_name' => 'Ime:',
		'fe_users.last_name' => 'Prezime:',
		'fe_users.module_sys_dmail_html' => 'Primanje emaila u HTML formatu?',
		'fe_users.date_of_birth' => 'Datum roрenja:',
		'fe_users.gender' => 'Gdin/Gрa',
		'fe_users.gender.I.0' => 'g.',
		'fe_users.gender.I.1' => 'gрa.',
		'fe_users.status' => 'Status:',
		'fe_users.status.I.1' => 'Student',
		'fe_users.status.I.2' => 'Traћim posao',
		'fe_users.status.I.3' => 'Radim',
		'fe_users.status.I.4' => 'Umirovljen',
		'fe_users.comments' => 'Komentari:',
	),
	'hu' => Array (
		'tt_content.list_type' => 'Frontend felhasznбlу regisztrбciу',
		'fe_users.static_info_country' => 'Orszбg:',
		'fe_users.zone' => 'Бllam/tartomбny:',
		'fe_users.language' => 'Nyelv:',
		'fe_users.first_name' => 'Keresztnйv:',
		'fe_users.last_name' => 'Vezetйknйv:',
		'fe_users.module_sys_dmail_html' => 'HTML formбtumъ email fogadбsa?',
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'tt_content.list_type' => 'Cadastro de Usuбrios do Site',
		'fe_users.static_info_country' => 'Paнs:',
		'fe_users.zone' => 'Estado/ Provнncia:',
		'fe_users.language' => 'Idioma:',
		'fe_users.first_name' => 'Nome:',
		'fe_users.last_name' => 'Sobrenome:',
		'fe_users.date_of_birth' => 'Data de nascimento:',
		'fe_users.gender' => 'Sr/Sra:',
		'fe_users.gender.I.0' => 'Sr',
		'fe_users.gender.I.1' => 'Sra',
		'fe_users.status' => 'Situaзгo:',
		'fe_users.status.I.1' => 'Estudante',
		'fe_users.status.I.2' => 'Desempregado',
		'fe_users.status.I.3' => 'Empregado',
		'fe_users.status.I.4' => 'Aposentado',
		'fe_users.comments' => 'Comentбrios:',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>