<?php
/**
 * Language labels for database tables/fields belonging to extension "sr_feuser_register"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'tt_content.list_type' => 'Front End User Registration',
 		'tt_content.pi1_flexform.display_mode' => 'Display mode',
		'tt_content.pi1_flexform.display_mode.1' => 'Not set',
 		'tt_content.pi1_flexform.display_mode.3' => 'Create',
		'tt_content.pi1_flexform.display_mode.5' => 'Invite',
 		'tt_content.pi1_flexform.display_mode.7' => 'Edit',
		'fe_users.static_info_country' => 'Country:',
		'fe_users.zone' => 'State/province:',
		'fe_users.language' => 'Language:',
		'fe_users.first_name' => 'First Name:',
		'fe_users.last_name' => 'Last Name:',
		'fe_users.module_sys_dmail_category' => 'Receive news on any of these subjects?',
		'fe_users.module_sys_dmail_category.I.1' => 'Subject 1',
		'fe_users.module_sys_dmail_category.I.2' => 'Subject 2',
		'fe_users.module_sys_dmail_category.I.3' => 'Subject 3',
		'fe_users.module_sys_dmail_category.I.4' => 'Subject 4',
		'fe_users.module_sys_dmail_category.I.5' => 'Subject 5',
		'fe_users.module_sys_dmail_category.I.6' => 'Subject 6',
		'fe_users.module_sys_dmail_category.I.7' => 'Subject 7',
		'fe_users.module_sys_dmail_category.I.8' => 'Subject 8',
		'fe_users.module_sys_dmail_category.I.9' => 'Subject 9',
		'fe_users.module_sys_dmail_category.I.10' => 'Subject 10',
		'fe_users.module_sys_dmail_html' => 'Receive emails in HTML format?',
		'fe_users.date_of_birth' => 'Date of birth:',
		'fe_users.gender' => 'Mr/Ms:',
		'fe_users.gender.I.0' => 'Mr',
		'fe_users.gender.I.1' => 'Ms',
		'fe_users.status' => 'Status:',
		'fe_users.status.I.1' => 'Student',
		'fe_users.status.I.2' => 'Job seeking',
		'fe_users.status.I.3' => 'Working',
		'fe_users.status.I.4' => 'Retired',
		'fe_users.comments' => 'Comments:',
		'fe_users.by_invitation' => 'Was invited:',
		'fe_groups_language_overlay' => 'User Group Alternative Language',
		'fe_groups_language_overlay.title' => 'Translated user group name',
	),
	'dk' => Array (
		'tt_content.list_type' => 'Front End Bruger Registrering',
		'fe_users.static_info_country' => 'Land:',
		'fe_users.zone' => 'Stat/Provins/Amt:',
		'fe_users.language' => 'Sprog:',
	),
	'de' => Array (
		'tt_content.list_type' => 'Front End Benutzer Registrierung',
		'fe_users.static_info_country' => 'Land:',
		'fe_users.zone' => 'Bundesland / Staat / Provinz:',
		'fe_users.language' => 'Sprache:',
		'fe_users.first_name' => 'Vorname:',
		'fe_users.last_name' => 'Nachname:',
		'fe_users.module_sys_dmail_category' => 'Mцchten Sie News zu folgenden Themen erhalten?',
		'fe_users.module_sys_dmail_category.I.1' => 'Thema 1',
		'fe_users.module_sys_dmail_category.I.2' => 'Thema 2',
		'fe_users.module_sys_dmail_category.I.3' => 'Thema 3',
		'fe_users.module_sys_dmail_category.I.4' => 'Thema 4',
		'fe_users.module_sys_dmail_category.I.5' => 'Thema 5',
		'fe_users.module_sys_dmail_category.I.6' => 'Thema 6',
		'fe_users.module_sys_dmail_category.I.7' => 'Thema 7',
		'fe_users.module_sys_dmail_category.I.8' => 'Thema 8',
		'fe_users.module_sys_dmail_category.I.9' => 'Thema 9',
		'fe_users.module_sys_dmail_category.I.10' => 'Thema 10',
		'fe_users.module_sys_dmail_html' => 'E-Mails im HTML-Format erhalten?',
		'fe_users.date_of_birth' => 'Geburtsdatum:',
		'fe_users.gender' => 'Hr./Fr.:',
		'fe_users.gender.I.0' => 'Hr.',
		'fe_users.gender.I.1' => 'Fr.',
		'fe_users.status' => 'Status:',
		'fe_users.status.I.1' => 'Student',
		'fe_users.status.I.2' => 'Schьler',
		'fe_users.status.I.3' => 'Angestellt',
		'fe_users.status.I.4' => 'Selbststдndig',
		'fe_users.comments' => 'Kommentare:',
	),
	'no' => Array (
		'tt_content.list_type' => 'Registering av Front End brukere',
		'fe_users.static_info_country' => 'Land:',
		'fe_users.zone' => 'Fylke:',
		'fe_users.language' => 'Sprеk:',
		'fe_users.first_name' => 'Fornavn:',
		'fe_users.last_name' => 'Etternavn:',
		'fe_users.module_sys_dmail_html' => 'Motta epost i HTML format?',
		'fe_users.date_of_birth' => 'Fшdt dato:',
	),
	'it' => Array (
		'tt_content.list_type' => 'Registrazione Utenti Frontend',
		'fe_users.static_info_country' => 'Stato:',
		'fe_users.zone' => 'Provincia:',
		'fe_users.language' => 'Lingua:',
		'fe_users.first_name' => 'Nome:',
		'fe_users.last_name' => 'Cognome:',
		'fe_users.module_sys_dmail_category' => 'Desideri ricevere novitа riguardo qualcuno dei seguenti argomenti?',
		'fe_users.module_sys_dmail_category.I.1' => 'Argomento 1',
		'fe_users.module_sys_dmail_category.I.2' => 'Argomento 2',
		'fe_users.module_sys_dmail_category.I.3' => 'Argomento 3',
		'fe_users.module_sys_dmail_category.I.4' => 'Argomento 4',
		'fe_users.module_sys_dmail_category.I.5' => 'Argomento 5',
		'fe_users.module_sys_dmail_category.I.6' => 'Argomento 6',
		'fe_users.module_sys_dmail_category.I.7' => 'Argomento 7',
		'fe_users.module_sys_dmail_category.I.8' => 'Argomento 8',
		'fe_users.module_sys_dmail_category.I.9' => 'Argomento 9',
		'fe_users.module_sys_dmail_category.I.10' => 'Argomento 10',
		'fe_users.module_sys_dmail_html' => 'Vuoi ricevere le email in formato HTML?',
		'fe_users.date_of_birth' => 'Data di nascita:',
		'fe_users.gender' => 'Signor/Signora:',
		'fe_users.gender.I.0' => 'Signor',
		'fe_users.gender.I.1' => 'Signora',
		'fe_users.status' => 'Situazione lavorativa:',
		'fe_users.status.I.1' => 'Studente',
		'fe_users.status.I.2' => 'In cerca di lavoro',
		'fe_users.status.I.3' => 'Occupato',
		'fe_users.status.I.4' => 'Pensionato',
		'fe_users.comments' => 'Commenti',
		'fe_groups_language_overlay' => 'Gruppo Utenti: lingua alternativa',
		'fe_groups_language_overlay.title' => 'Gruppo Utenti (tradotto):',
	),
	'fr' => Array (
		'tt_content.list_type' => 'Enregistrement des utilisateurs de l\'avant-plan',
 		'tt_content.pi1_flexform.display_mode' => 'Mode d\'affichage',
 		'tt_content.pi1_flexform.display_mode.1' => 'Non spйcifiй',
 		'tt_content.pi1_flexform.display_mode.3' => 'Crйation',
		'tt_content.pi1_flexform.display_mode.5' => 'Invitation',
 		'tt_content.pi1_flexform.display_mode.7' => 'Mise а jour',
		'fe_users.static_info_country' => 'Pays:',
		'fe_users.zone' => 'Йtat/province:',
		'fe_users.language' => 'Langue:',
		'fe_users.first_name' => 'Prйnom:',
		'fe_users.last_name' => 'Nom:',
		'fe_users.module_sys_dmail_category' => 'Recevoir des bulletins sur l\'un ou l\'autre de ces sujets?',
		'fe_users.module_sys_dmail_category.I.1' => 'Sujet 1',
		'fe_users.module_sys_dmail_category.I.2' => 'Sujet 2',
		'fe_users.module_sys_dmail_category.I.3' => 'Sujet 3',
		'fe_users.module_sys_dmail_category.I.4' => 'Sujet 4',
		'fe_users.module_sys_dmail_category.I.5' => 'Sujet 5',
		'fe_users.module_sys_dmail_category.I.6' => 'Sujet 6',
		'fe_users.module_sys_dmail_category.I.7' => 'Sujet 7',
		'fe_users.module_sys_dmail_category.I.8' => 'Sujet 8',
		'fe_users.module_sys_dmail_category.I.9' => 'Sujet 9',
		'fe_users.module_sys_dmail_category.I.10' => 'Sujet 10',
		'fe_users.module_sys_dmail_html' => 'Recevoir les messages en format HTML?',
		'fe_users.date_of_birth' => 'Date de naissance:',
		'fe_users.gender' => 'M./Mme:',
		'fe_users.gender.I.0' => 'M.',
		'fe_users.gender.I.1' => 'Mme',
		'fe_users.status' => 'Statut:',
		'fe_users.status.I.1' => 'Aux йtudes',
		'fe_users.status.I.2' => 'En recherche d\'emploi',
		'fe_users.status.I.3' => 'Au travail',
		'fe_users.status.I.4' => 'А la retraite',
		'fe_users.comments' => 'Commentaires:',
		'fe_users.by_invitation' => 'Invitй(e):',
		'fe_groups_language_overlay' => 'Langue alternative de groupe d\'utilisateurs',
		'fe_groups_language_overlay.title' => 'Traduction du nom de groupe',
	),
	'es' => Array (
		'tt_content.list_type' => 'Registro de los usuarios del frontend',
		'fe_users.static_info_country' => 'Paнs:',
		'fe_users.zone' => 'Estado/provincia:',
		'fe_users.language' => 'Idioma:',
		'fe_users.first_name' => 'Nombre:',
		'fe_users.last_name' => 'Apellido:',
		'fe_users.module_sys_dmail_category' => 'їRecibir noticias sobre alguno de estos asuntos?',
		'fe_users.module_sys_dmail_category.I.1' => 'Asunto 1',
		'fe_users.module_sys_dmail_category.I.2' => 'Asunto 2',
		'fe_users.module_sys_dmail_category.I.3' => 'Asunto 3',
		'fe_users.module_sys_dmail_category.I.4' => 'Asunto 4',
		'fe_users.module_sys_dmail_category.I.5' => 'Asunto 5',
		'fe_users.module_sys_dmail_category.I.6' => 'Asunto 6',
		'fe_users.module_sys_dmail_category.I.7' => 'Asunto 7',
		'fe_users.module_sys_dmail_category.I.8' => 'Asunto 8',
		'fe_users.module_sys_dmail_category.I.9' => 'Asunto 9',
		'fe_users.module_sys_dmail_category.I.10' => 'Asunto 10',
		'fe_users.module_sys_dmail_html' => 'їRecibir correos en formato HTML?',
		'fe_users.date_of_birth' => 'Fecha de nacimiento:',
		'fe_users.gender' => 'Sr./Sra.:',
		'fe_users.gender.I.0' => 'Sr.',
		'fe_users.gender.I.1' => 'Sra.',
		'fe_users.status' => 'Estado:',
		'fe_users.status.I.1' => 'Estudiantes',
		'fe_users.status.I.2' => 'Buscando trabajo',
		'fe_users.status.I.3' => 'Trabajando',
		'fe_users.status.I.4' => 'Jubilado',
		'fe_users.comments' => 'Comentarios:',
	),
	'nl' => Array (
		'tt_content.list_type' => 'Frontend Gebruikersregistratie',
		'fe_users.static_info_country' => 'Land:',
		'fe_users.zone' => 'Provincie:',
		'fe_users.language' => 'Taal:',
		'fe_users.first_name' => 'Voornaam:',
		'fe_users.last_name' => 'Achternaam:',
		'fe_users.module_sys_dmail_category' => 'Nieuws ontvangen van deze onderwerpen?',
		'fe_users.module_sys_dmail_category.I.1' => 'Onderwerp 1',
		'fe_users.module_sys_dmail_category.I.2' => 'Onderwerp 2',
		'fe_users.module_sys_dmail_category.I.3' => 'Onderwerp 3',
		'fe_users.module_sys_dmail_category.I.4' => 'Onderwerp 4',
		'fe_users.module_sys_dmail_category.I.5' => 'Onderwerp 5',
		'fe_users.module_sys_dmail_category.I.6' => 'Onderwerp 6',
		'fe_users.module_sys_dmail_category.I.7' => 'Onderwerp 7',
		'fe_users.module_sys_dmail_category.I.8' => 'Onderwerp 8',
		'fe_users.module_sys_dmail_category.I.9' => 'Onderwerp 9',
		'fe_users.module_sys_dmail_category.I.10' => 'Onderwerp 10',
		'fe_users.module_sys_dmail_html' => 'Emails in HTML formaat ontvangen?',
		'fe_users.date_of_birth' => 'Geboortedatum:',
		'fe_users.gender' => 'Dhr/Mevr:',
		'fe_users.gender.I.0' => 'Dhr',
		'fe_users.gender.I.1' => 'Mevr',
		'fe_users.status' => 'Status:',
		'fe_users.status.I.1' => 'Student',
		'fe_users.status.I.2' => 'Op zoek naar een baan',
		'fe_users.status.I.3' => 'Werkend',
		'fe_users.status.I.4' => 'Met pensioen',
		'fe_users.comments' => 'Commentaar:',
	),
	'cz' => Array (
		'tt_content.list_type' => 'Registrace uћivatelщ frontendu',
		'fe_users.static_info_country' => 'Zemм:',
		'fe_users.zone' => 'Stбt/kraj:',
		'fe_users.language' => 'Jazyk:',
		'fe_users.first_name' => 'Jmйno:',
		'fe_users.last_name' => 'Pшнjmenн:',
		'fe_users.module_sys_dmail_category' => 'Dostбvat aktuality z nмkterй z tмchto oblastн?',
		'fe_users.module_sys_dmail_category.I.1' => 'Oblast 1',
		'fe_users.module_sys_dmail_category.I.2' => 'Oblast 2',
		'fe_users.module_sys_dmail_category.I.3' => 'Oblast 3',
		'fe_users.module_sys_dmail_category.I.4' => 'Oblast 4',
		'fe_users.module_sys_dmail_category.I.5' => 'Oblast 5',
		'fe_users.module_sys_dmail_category.I.6' => 'Oblast 6',
		'fe_users.module_sys_dmail_category.I.7' => 'Oblast 7',
		'fe_users.module_sys_dmail_category.I.8' => 'Oblast 8',
		'fe_users.module_sys_dmail_category.I.9' => 'Oblast 9',
		'fe_users.module_sys_dmail_category.I.10' => 'Oblast 10',
		'fe_users.module_sys_dmail_html' => 'Dostбvat e-maily v HTML formбtu?',
		'fe_users.date_of_birth' => 'Datum narozenн',
		'fe_users.gender' => 'Muћ/Ћena:',
		'fe_users.gender.I.0' => 'muћ',
		'fe_users.gender.I.1' => 'ћena',
		'fe_users.status' => 'Stav:',
		'fe_users.status.I.1' => 'Student',
		'fe_users.status.I.2' => 'Nezamмstnanэ',
		'fe_users.status.I.3' => 'Zamмstnanэ',
		'fe_users.status.I.4' => 'V dщchodu',
		'fe_users.comments' => 'Poznбmky',
	),
	'pl' => Array (
		'tt_content.list_type' => 'Rejesteracja uїytkownikуw zewnкtrznych',
		'fe_users.static_info_country' => 'Kraj:',
		'fe_users.zone' => 'Wojewуdztwo:',
		'fe_users.language' => 'Jкzyk:',
		'fe_users.first_name' => 'Imiк:',
		'fe_users.last_name' => 'Nazwisko:',
		'fe_users.module_sys_dmail_html' => 'Otrzymuje emaile w HTML?',
		'fe_users.date_of_birth' => 'Data urodzenia',
	),
	'si' => Array (
	),
	'fi' => Array (
		'tt_content.list_type' => 'FE kдyttдjдn rekisterцinti',
		'fe_users.static_info_country' => 'Maa:',
		'fe_users.zone' => 'Osavaltio/provinssi:',
		'fe_users.language' => 'Kieli:',
		'fe_users.first_name' => 'Etunimi:',
		'fe_users.last_name' => 'Sukunimi:',
		'fe_users.module_sys_dmail_category' => 'Haluatko vastaanottaa uutisia joistan nдistд aihepiireistд ?',
		'fe_users.module_sys_dmail_category.I.1' => 'Aihepiiri 1',
		'fe_users.module_sys_dmail_category.I.2' => 'Aihepiiri 2',
		'fe_users.module_sys_dmail_category.I.3' => 'Aihepiiri 3',
		'fe_users.module_sys_dmail_category.I.4' => 'Aihepiiri 4',
		'fe_users.module_sys_dmail_category.I.5' => 'Aihepiiri 5',
		'fe_users.module_sys_dmail_category.I.6' => 'Aihepiiri 6',
		'fe_users.module_sys_dmail_category.I.7' => 'Aihepiiri 7',
		'fe_users.module_sys_dmail_category.I.8' => 'Aihepiiri 8',
		'fe_users.module_sys_dmail_category.I.9' => 'Aihepiiri 9',
		'fe_users.module_sys_dmail_category.I.10' => 'Aihepiiri 10',
		'fe_users.module_sys_dmail_html' => 'Haluatko vastaanottaa sдhkцpostit HTML-muodossa ?',
		'fe_users.date_of_birth' => 'Syntymдaika:',
		'fe_users.gender' => 'Mr/Ms:',
		'fe_users.gender.I.0' => 'Mr',
		'fe_users.gender.I.1' => 'Ms',
		'fe_users.status' => 'Tila:',
		'fe_users.status.I.1' => 'Opiskelija',
		'fe_users.status.I.2' => 'Tyцtцn',
		'fe_users.status.I.3' => 'Tyцtekijд',
		'fe_users.status.I.4' => 'Elдkelдinen',
		'fe_users.comments' => 'Kommentit:',
	),
	'tr' => Array (
		'tt_content.list_type' => 'Websitesi Kullanэcэ Kayэt Эюlemi',
		'fe_users.static_info_country' => 'Ьlke:',
		'fe_users.zone' => 'Eyalet/Эl:',
		'fe_users.language' => 'Dil:',
		'fe_users.first_name' => 'Ad:',
		'fe_users.last_name' => 'Soyad:',
		'fe_users.module_sys_dmail_category' => 'Bu konularэn herhangi biri hakkэnda haber alэnsэn mэ?',
		'fe_users.module_sys_dmail_category.I.1' => 'Konu 1',
		'fe_users.module_sys_dmail_category.I.2' => 'Konu 2',
		'fe_users.module_sys_dmail_category.I.3' => 'Konu 3',
		'fe_users.module_sys_dmail_category.I.4' => 'Konu 4',
		'fe_users.module_sys_dmail_category.I.5' => 'Konu 5',
		'fe_users.module_sys_dmail_category.I.6' => 'Konu 6',
		'fe_users.module_sys_dmail_category.I.7' => 'Konu 7',
		'fe_users.module_sys_dmail_category.I.8' => 'Konu 8',
		'fe_users.module_sys_dmail_category.I.9' => 'Konu 9',
		'fe_users.module_sys_dmail_category.I.10' => 'Konu 10',
		'fe_users.module_sys_dmail_html' => 'E-postalar HTML formatэnda mэ alэnsэn?',
		'fe_users.date_of_birth' => 'Doрum tarihi:',
		'fe_users.gender' => 'Bay/Bayan',
		'fe_users.gender.I.0' => 'Bay',
		'fe_users.gender.I.1' => 'Bayan',
		'fe_users.status' => 'Mesleрi:',
		'fe_users.status.I.1' => 'Црrenci',
		'fe_users.status.I.2' => 'Эю arayan',
		'fe_users.status.I.3' => 'Зalэюan',
		'fe_users.status.I.4' => 'Emekli',
		'fe_users.comments' => 'Yorumlar:',
		'fe_groups_language_overlay' => 'Kullanэcэ Grubu Alternatif Dili',
		'fe_groups_language_overlay.title' => 'Зevrilen kullanэcэ grubu adэ',
	),
	'se' => Array (
		'tt_content.list_type' => 'Registrering av Front End-anvдndare',
		'fe_users.static_info_country' => 'Land:',
		'fe_users.zone' => 'Stat/provins:',
		'fe_users.language' => 'Sprеk:',
		'fe_users.first_name' => 'Fцrnamn:',
		'fe_users.last_name' => 'Efternamn:',
		'fe_users.module_sys_dmail_html' => 'Ta emot epost i HTML-format?',
		'fe_users.date_of_birth' => 'Fцdelsetid:',
	),
	'pt' => Array (
	),
	'ru' => Array (
		'tt_content.list_type' => 'Регистрация пользователей на веб-сайте',
		'fe_users.static_info_country' => 'Страна:',
		'fe_users.zone' => 'Район/область:',
		'fe_users.language' => 'Язык:',
		'fe_users.first_name' => 'Имя:',
		'fe_users.last_name' => 'Фамилия:',
		'fe_users.module_sys_dmail_category' => 'Вы хотите получать новости по этим темам?',
		'fe_users.module_sys_dmail_category.I.1' => 'Тема 1',
		'fe_users.module_sys_dmail_category.I.2' => 'Тема 2',
		'fe_users.module_sys_dmail_category.I.3' => 'Тема 3',
		'fe_users.module_sys_dmail_category.I.4' => 'Тема 4',
		'fe_users.module_sys_dmail_category.I.5' => 'Тема 5',
		'fe_users.module_sys_dmail_category.I.6' => 'Тема 6',
		'fe_users.module_sys_dmail_category.I.7' => 'Тема 7',
		'fe_users.module_sys_dmail_category.I.8' => 'Тема 8',
		'fe_users.module_sys_dmail_category.I.9' => 'Тема 9',
		'fe_users.module_sys_dmail_category.I.10' => 'Тема 10',
		'fe_users.module_sys_dmail_html' => 'Получать эл.почту в формате HTML?',
		'fe_users.date_of_birth' => 'Дата рождения:',
		'fe_users.gender' => 'Господин / Госпожа:',
		'fe_users.gender.I.0' => 'Господин',
		'fe_users.gender.I.1' => 'Госпожа',
		'fe_users.status' => 'Статус',
		'fe_users.status.I.1' => 'Студент',
		'fe_users.status.I.2' => 'Ищущий работу',
		'fe_users.status.I.3' => 'Работающий',
		'fe_users.status.I.4' => 'Пенсионер',
		'fe_users.comments' => 'Комментарии:',
		'fe_groups_language_overlay' => 'Альтернативный язык группы пользователей',
		'fe_groups_language_overlay.title' => 'Переведённое название группы',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
		'tt_content.list_type' => 'Registracija frontend korisnika:',
		'fe_users.static_info_country' => 'Drћava:',
		'fe_users.zone' => 'Regija/ћupanija:',
		'fe_users.language' => 'Jezik:',
		'fe_users.first_name' => 'Ime:',
		'fe_users.last_name' => 'Prezime:',
		'fe_users.module_sys_dmail_html' => 'Primanje emaila u HTML formatu?',
		'fe_users.date_of_birth' => 'Datum roрenja:',
		'fe_users.gender' => 'Gdin/Gрa',
		'fe_users.gender.I.0' => 'g.',
		'fe_users.gender.I.1' => 'gрa.',
		'fe_users.status' => 'Status:',
		'fe_users.status.I.1' => 'Student',
		'fe_users.status.I.2' => 'Traћim posao',
		'fe_users.status.I.3' => 'Radim',
		'fe_users.status.I.4' => 'Umirovljen',
		'fe_users.comments' => 'Komentari:',
	),
	'hu' => Array (
		'tt_content.list_type' => 'Frontend felhasznбlу regisztrбciу',
		'fe_users.static_info_country' => 'Orszбg:',
		'fe_users.zone' => 'Бllam/tartomбny:',
		'fe_users.language' => 'Nyelv:',
		'fe_users.first_name' => 'Keresztnйv:',
		'fe_users.last_name' => 'Vezetйknйv:',
		'fe_users.module_sys_dmail_html' => 'HTML formбtumъ email fogadбsa?',
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'tt_content.list_type' => 'Cadastro de Usuбrios do Site',
		'fe_users.static_info_country' => 'Paнs:',
		'fe_users.zone' => 'Estado/ Provнncia:',
		'fe_users.language' => 'Idioma:',
		'fe_users.first_name' => 'Nome:',
		'fe_users.last_name' => 'Sobrenome:',
		'fe_users.module_sys_dmail_category' => 'Receber notнcias sobre qualquer um destes assuntos?',
		'fe_users.module_sys_dmail_category.I.1' => 'Assunto 1',
		'fe_users.module_sys_dmail_category.I.2' => 'Assunto 2',
		'fe_users.module_sys_dmail_category.I.3' => 'Assunto 3',
		'fe_users.module_sys_dmail_category.I.4' => 'Assunto 4',
		'fe_users.module_sys_dmail_category.I.5' => 'Assunto 5',
		'fe_users.module_sys_dmail_category.I.6' => 'Assunto 6',
		'fe_users.module_sys_dmail_category.I.7' => 'Assunto 7',
		'fe_users.module_sys_dmail_category.I.8' => 'Assunto 8',
		'fe_users.module_sys_dmail_category.I.9' => 'Assunto 9',
		'fe_users.module_sys_dmail_category.I.10' => 'Assunto 10',
		'fe_users.module_sys_dmail_html' => 'Receber e-mails em HTML?',
		'fe_users.date_of_birth' => 'Data de nascimento:',
		'fe_users.gender' => 'Sr/Sra:',
		'fe_users.gender.I.0' => 'Sr',
		'fe_users.gender.I.1' => 'Sra',
		'fe_users.status' => 'Situaзгo:',
		'fe_users.status.I.1' => 'Estudante',
		'fe_users.status.I.2' => 'Desempregado',
		'fe_users.status.I.3' => 'Empregado',
		'fe_users.status.I.4' => 'Aposentado',
		'fe_users.comments' => 'Comentбrios:',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>